// Auto-generated: registers ALL WA free components as beta-*
import './animated-image/animated-image.js'; // beta-animated-image
import './animation/animation.js'; // beta-animation
import './avatar/avatar.js'; // beta-avatar
import './badge/badge.js'; // beta-badge
import './breadcrumb/breadcrumb.js'; // beta-breadcrumb
import './breadcrumb-item/breadcrumb-item.js'; // beta-breadcrumb-item
import './button/button.js'; // beta-button
import './button-group/button-group.js'; // beta-button-group
import './callout/callout.js'; // beta-callout
import './card/card.js'; // beta-card
import './carousel/carousel.js'; // beta-carousel
import './carousel-item/carousel-item.js'; // beta-carousel-item
import './checkbox/checkbox.js'; // beta-checkbox
import './color-picker/color-picker.js'; // beta-color-picker
import './comparison/comparison.js'; // beta-comparison
import './copy-button/copy-button.js'; // beta-copy-button
import './details/details.js'; // beta-details
import './dialog/dialog.js'; // beta-dialog
import './divider/divider.js'; // beta-divider
import './drawer/drawer.js'; // beta-drawer
import './dropdown/dropdown.js'; // beta-dropdown
import './dropdown-item/dropdown-item.js'; // beta-dropdown-item
import './format-bytes/format-bytes.js'; // beta-format-bytes
import './format-date/format-date.js'; // beta-format-date
import './format-number/format-number.js'; // beta-format-number
import './icon/icon.js'; // beta-icon
import './include/include.js'; // beta-include
import './input/input.js'; // beta-input
import './intersection-observer/intersection-observer.js'; // beta-intersection-observer
import './mutation-observer/mutation-observer.js'; // beta-mutation-observer
import './number-input/number-input.js'; // beta-number-input
import './option/option.js'; // beta-option
import './popover/popover.js'; // beta-popover
import './popup/popup.js'; // beta-popup
import './progress-bar/progress-bar.js'; // beta-progress-bar
import './progress-ring/progress-ring.js'; // beta-progress-ring
import './qr-code/qr-code.js'; // beta-qr-code
import './radio/radio.js'; // beta-radio
import './radio-group/radio-group.js'; // beta-radio-group
import './rating/rating.js'; // beta-rating
import './relative-time/relative-time.js'; // beta-relative-time
import './resize-observer/resize-observer.js'; // beta-resize-observer
import './scroller/scroller.js'; // beta-scroller
import './select/select.js'; // beta-select
import './skeleton/skeleton.js'; // beta-skeleton
import './slider/slider.js'; // beta-slider
import './spinner/spinner.js'; // beta-spinner
import './split-panel/split-panel.js'; // beta-split-panel
import './switch/switch.js'; // beta-switch
import './tab/tab.js'; // beta-tab
import './tab-group/tab-group.js'; // beta-tab-group
import './tab-panel/tab-panel.js'; // beta-tab-panel
import './tag/tag.js'; // beta-tag
import './textarea/textarea.js'; // beta-textarea
import './tooltip/tooltip.js'; // beta-tooltip
import './tree/tree.js'; // beta-tree
import './tree-item/tree-item.js'; // beta-tree-item
import './zoomable-frame/zoomable-frame.js'; // beta-zoomable-frame
