#!/usr/bin/env node
// Token build step: CSS → SCSS + TS + JSON exports

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, '..');
const themesDir = resolve(rootDir, 'src/themes');
const outDir = resolve(rootDir, 'dist/tokens');

function extractTokens(css) {
  const tokens = [];
  const re = /(--[\w-]+)\s*:\s*([^;}]+)/g;
  let match;
  while ((match = re.exec(css)) !== null) {
    tokens.push({ name: match[1].trim(), value: match[2].trim() });
  }
  return tokens;
}

function tokenNameToTsConst(name) {
  return name
    .replace(/^--/, '')
    .replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

const files = ['shared.css', 'light.css', 'dark.css'];
const allTokens = [];
const seen = new Set();

for (const file of files) {
  const css = readFileSync(resolve(themesDir, file), 'utf-8');
  for (const token of extractTokens(css)) {
    if (!seen.has(token.name)) {
      seen.add(token.name);
      allTokens.push(token);
    }
  }
}

mkdirSync(outDir, { recursive: true });

const scssLines = allTokens.map((t) => `${t.name.replace(/^--/, '$')}: ${t.value};`);
writeFileSync(resolve(outDir, 'variables.scss'),
  '// Auto-generated by @adesso-forge/adforge-beta — do not edit manually\n\n' + scssLines.join('\n') + '\n');

const tsLines = allTokens.map((t) => `export const ${tokenNameToTsConst(t.name)} = ${JSON.stringify(t.value)} as const;`);
writeFileSync(resolve(outDir, 'tokens.ts'),
  '// Auto-generated by @adesso-forge/adforge-beta — do not edit manually\n\n' + tsLines.join('\n') + '\n');

writeFileSync(resolve(outDir, 'tokens.json'),
  JSON.stringify({ generated: new Date().toISOString(), tokens: allTokens }, null, 2) + '\n');

console.log(`✓ Generated ${allTokens.length} tokens → dist/tokens/{variables.scss, tokens.ts, tokens.json}`);
